### PR TITLE
Checking for 200 response in ZTFTriggerHandler's async put method.

### PR DESCRIPTION
**Pull request by guiga004**

### CODE REVIEW

**Comment by guiga004** [comment]
@mcoughlin @stefanv

**Comment by mcoughlin** [comment]
@stefanv @guiga004  My inuition is that we should still throw an error for a repeated call to the queue, but something other than the usual code. What do you think?

**Comment by stefanv** [comment]
I'm confused; they return 200 when there's a failure to submit?

**Comment by mcoughlin** [comment]
@stefanv yeah 200 for repeated queue and 201 for success.

**Comment by stefanv** [comment]
What about https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

**Comment by guiga004** [comment]
@mcoughlin , @stefanv - So, we are throwing an error like this then:

self.error(message=f"Submitted queue {data['queue_name']} already exists")

Should we also be checking for code 409 then for this error, or throwing it for 200 still?

**Comment by mcoughlin** [comment]
@guiga004 yes an error, but setting request_code=409 or whatever the right name is.

**Comment by guiga004** [comment]
@mcoughlin - please see latest push

**Comment by mcoughlin** [comment]
@guiga004 could you fix the linting?

**Comment by guiga004** [comment]
@mcoughlin - fixed the linting

**Comment by stefanv** [comment]
Looks good; would be good to check if any tests need to be added/updated (I am not familiar enough with the Kowalski testing setup to know).

**Comment by mcoughlin** [comment]
@stefanv For testing, we just test the creation of the request, not actually send it to and from ZTF, so this one won't beupdated.

**Comment by mcoughlin** [comment]
@dmitryduev Maybe we also get this in there?

**Review by dmitryduev — APPROVED** [review]
👍🏻

**Pull request merged**
