### PR TITLE
Port of #28: Updated CLU crossmatch section to physical units

### PR DESCRIPTION
**Pull request by dmitryduev**
Improved readability and ported @dekishalay's code to the new `dask`-based broker.

### CODE REVIEW

**Comment by dmitryduev** [comment]
Diff will look much better once #29 is merged.

**Comment by dekishalay** [comment]
Just got a confirmed decision from the team -- we would like to keep the cross-match volume at 200 Mpc, but set the cross-match radius at 100 kpc like in this PR. @dmitryduev Would it be better to rename this branch to clu-100kpc instead of clu-150mpc?

**Comment by dmitryduev** [comment]
@dekishalay it doesn't really matter what you call the branch -- I'll delete it anyways once this is merged. 
What about the code, looks good?

**Comment by dekishalay** [comment]
I removed the check for in_volume, to keep the volume at the full 200 Mpc. @dmitryduev If the code looks fine to you, we are good to go.

**Pull request merged**
