### PR TITLE
Updated CLU cross-match to 50 kpc

### PR DESCRIPTION
**Pull request by dekishalay**
Also added distance_kpc for physical distance to cross-matched galaxies

### CODE REVIEW

**Comment by dannygoldstein** [comment]
@dekishalay Looks like there are some merge conflicts. Can you resolve those on the command line so the tests and CI can run?

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

**Comment by dmitryduev** [comment]
thanks @dekishalay! Please pull in the latest master, that should probably resolve the conflict. Also, please make sure to install our pre-commit hook:
```
pip install pre-commit
pre-commit install
```

**Comment by dmitryduev** [comment]
@dekishalay another note: you are implementing your changes on your master branch; it's better to create a dedicated branch (so that, for example, if someone wants to submit a PR to it, they'll be able to do it). 
We have very good dev guidelines on Fritz [here](https://docs.fritz.science/developer.html). It might be a good idea to make Kowalski's own docs page as opposed to just dumping everything to readme...

**Comment by dmitryduev** [comment]
@dekishalay just updated the developer guidelines, please take a look: https://github.com/dmitryduev/kowalski#developer-guidelines

**Pull request closed without merging**
