### PR TITLE
Add field/ccd/quad info to ZTF source features

### PR DESCRIPTION
**Pull request by dmitryduev**

### CODE REVIEW

**Review by mcoughlin — APPROVED** [review]
Huge thank you for doing this Dima.

**Comment by mcoughlin** [comment]
Did you also want @kmshin1397 to review? Or happy to merge?

**Comment by dmitryduev** [comment]
@mcoughlin good point, thanks. @kmshin1397 mind taking a quick look?

**Review by kmshin1397 — APPROVED** [review]
LGTM!

**Pull request merged**
