### PR TITLE
Add supervisord process to post daily performance reports to Slack

### PR DESCRIPTION
**Pull request by kmshin1397**
Example report generated from logs I transferred over to my machine from K yesterday:
[kowalski_perf_report_20210304 (1).pdf](https://github.com/dmitryduev/kowalski/files/6086712/kowalski_perf_report_20210304.1.pdf)

Screenshot of test messages to Slack:
image

Addresses #79

### CODE REVIEW

**Comment by kmshin1397** [comment]
Will need to add in the Slack API credentials when deploying

**Review by dmitryduev — CHANGES_REQUESTED** [review]
This is really nice, as always! Thanks @kmshin1397!

I have a few suggestions (mostly regarding the plots):
- I notice that for a number of actions, the max value is huge (like max: 1.5225e+18s). Where could those be coming from? I think it must be some junk that screws lines in the logs, so perhaps just throwing out anything that's >1h would be safe.
- I suggest displaying all histograms using the same x-range from 0 to 1 seconds, that should ease inspecting them
- Please move the text to the upper right corner of the plots, that way we'll save a lot of space in the resulting pdf.
- This one is optional, see how you feel about it: I think it would be very useful to plot all histograms on one graph and show it (with an external legend) on the first page of the report. It will be crowded for sure, but will immediately tell us if something is terribly off. Perhaps playing with alpha values and fitting each hist in some simple way and displaying just the fit curve would be sufficient to make it not too crowded.

**Comment by kmshin1397** [comment]
All good suggestions @dmitryduev! Here's an example PDF with the changes:
[kowalski_perf_report_20210305.pdf](https://github.com/dmitryduev/kowalski/files/6094171/kowalski_perf_report_20210305.pdf)

**Review by dmitryduev — COMMENTED** [review]
Thanks for addressing my feedback! One last thing and it should be good to go in: what happens if there's no data for the previous night?

**Comment by kmshin1397** [comment]
It will only generate plots for action types that there is data for. If there's no data of any kind, you would get the title page with no actual histograms I believe. Should I maybe include a message saying "No data" or something like that in that case?

**Review by dmitryduev — APPROVED** [review]

**Comment by dmitryduev** [comment]
That’s a good idea, please do. Feel free to self-merge afterwards!

**Pull request merged**
